nodes = [
  { name: "master", ip: "192.168.56.10", memory: 4096 },
  { name: "worker1", ip: "192.168.56.11", memory: 1024 },
  { name: "worker2", ip: "192.168.56.12", memory: 1024 }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.box = "ubuntu/focal64"
      vm.vm.hostname = node[:name]
      vm.vm.network "private_network", type: "static", ip: node[:ip]
      vm.config.vm.network "public_network", bridge: "enp1s0"
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = node[:memory]
        vb.cpus = 2
      end

      # Conditional provisioning based on the node type (master or worker)
      if node[:name] == "master"
        vm.vm.provision "shell", path: "script/master-setup.sh"
        vm.vm.provision "shell", inline: <<-SHELL
          sleep 60
        SHELL
      else
        vm.vm.provision "shell", path: "script/worker-setup.sh"
      end
    end
  end
end
