Vagrant.configure("2") do |config|
  # Define the master node
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/focal64"
    master.vm.hostname = "master-node"
    master.vm.network "private_network", type: "static", ip: "192.168.56.10"
    config.vm.network "public_network", bridge: "enp1s0"

    # Share the /etc/kubernetes folder from the master node to the worker nodes
    # master.vm.synced_folder "/home/md-omor/Documents/vm/cluster/k8s", "/etc/kubernetes", create: true

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    master.vm.provision "shell", path: "script/common.sh"
  end

  # Define the worker node
  config.vm.define "worker1" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", type: "static", ip: "192.168.56.11"
    config.vm.network "public_network", bridge: "enp1s0"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
    worker.vm.provision "shell", path: "script/common.sh"
  end

    # Define the worker node
  config.vm.define "worker2" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "worker2"
    worker.vm.network "private_network", type: "static", ip: "192.168.56.12"
    config.vm.network "public_network", bridge: "enp1s0"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
    worker.vm.provision "shell", path: "script/common.sh"
  end
end
