Vagrant.configure("2") do |config|
  # Define the master node
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/focal64"
    master.vm.hostname = "master-node"
    master.vm.network "private_network", type: "static", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl
      sudo apt-get update
      sudo snap install kubectl --classic
      sudo snap install kubeadm --classic
      sudo snap install kubelet --classic
      sudo apt-get install -y containerd
      sudo systemctl start containerd
      sudo systemctl enable containerd
      sudo swapoff -a
      # sudo systemctl enable kubelet
      # sudo systemctl start containerd

      # Set an alias for kubectl
      echo "alias k='kubectl'" >> ~/.bashrc
      source ~/.bashrc
    SHELL
  end

  # Define the worker node
  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "worker-node"
    worker.vm.network "private_network", type: "static", ip: "192.168.56.11"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl
      sudo apt-get update
      sudo snap install kubectl --classic
      sudo snap install kubeadm --classic
      sudo snap install kubelet --classic
      sudo apt-get install -y containerd
      sudo systemctl start containerd
      sudo systemctl enable containerd
      sudo swapoff -a
      # sudo systemctl enable kubelet
      # sudo systemctl start containerd

      # Set an alias for kubectl
      echo "alias k='kubectl'" >> ~/.bashrc
      source ~/.bashrc
    SHELL
  end
end
